name: Test PAT Access

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  test-pat-access:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Test PAT Access
      run: |
        echo "Testing PAT access"
        curl -H "Authorization: token ${{ secrets.SERVICE_ACCOUNT_PAT }}" \
          https://api.github.com/repos/${{ github.repository }}
